source "http://rubygems.org"

gemspec

platforms :jruby do
  gem 'jruby-openssl'
  gem 'puma'
end

group :development do
  gem "rack-test"
  gem "minitest"
  gem "simplecov"
  gem "webmock", '< 1.10'  # VCR wants that version
  gem "vcr"
  gem "aws"
  gem "profitbricks", :github => "dsander/profitbricks", :ref => 'eecc52d'
end

group :jenkins do
  gem 'turn'
  gem 'minitest-reporters', :platform => "ruby_19"
end
